import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
=======
>>>>>>> dc99e323869fd45501bf75e92d62a234996f0b73

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "exhibitPro",
=======
  title: "Create Next App",
>>>>>>> dc99e323869fd45501bf75e92d62a234996f0b73
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body className="antialiased">
        <main>{children}</main>
        <Footer></Footer>
=======
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
>>>>>>> dc99e323869fd45501bf75e92d62a234996f0b73
      </body>
    </html>
  );
}
